spring.application.name=projecttool


# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/project_tool?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kotlin2025}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LOGGING (DEV SAFE)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.error.whitelabel.enabled=false
